name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: rails_starter
          POSTGRES_PASSWORD: rails_starter
          POSTGRES_USER: rails_starter
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install javascript dependencies
        run: yarn install
      - name: Reset test database
        env:
          PGPASSWORD: rails_starter
          PGUSER: rails_starter
          RAILS_ENV: test
        run: bundle exec rails db:reset
      - name: Scan for Rails vulnerabilities
        env:
          RAILS_ENV: test
        run: bundle exec brakeman -A --color -o /dev/stdout
      - name: Lint Rails code
        run: bundle exec rubocop
      - name: Run Rails specs
        env:
          PGPASSWORD: rails_starter
          PGUSER: rails_starter
          RAILS_ENV: test
        run: bundle exec rake
      - name: Lint javascript/typescript
        run: yarn eslint app/javascript --ext .js,.jsx,.ts,.tsx
      - name: Run javascript/typescript specs
        run: yarn run test
